CREATE TABLE "hero_settings" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"eyebrow" varchar(255) NOT NULL,
	"heading_line_1" varchar(255) NOT NULL,
	"heading_line_2" varchar(255) NOT NULL,
	"rotating_words" text[] NOT NULL,
	"description" text NOT NULL,
	"primary_button_text" varchar(120) NOT NULL,
	"primary_button_link" varchar(500) NOT NULL,
	"secondary_button_text" varchar(120) NOT NULL,
	"secondary_button_link" varchar(500) NOT NULL,
	"trust_point_1" varchar(255) NOT NULL,
	"trust_point_2" varchar(255) NOT NULL,
	"trust_point_3" varchar(255) NOT NULL,
	"image" varchar(1000) NOT NULL,
	"image_alt" varchar(500) NOT NULL,
	"image_title" varchar(255) NOT NULL,
	"image_subtitle" varchar(255) NOT NULL,
	"image_badge" varchar(120) NOT NULL,
	"chip_1_title" varchar(255) NOT NULL,
	"chip_1_subtitle" varchar(255) NOT NULL,
	"chip_2_title" varchar(255) NOT NULL,
	"chip_2_subtitle" varchar(255) NOT NULL,
	"chip_3_title" varchar(255) NOT NULL,
	"chip_3_subtitle" varchar(255) NOT NULL,
	"is_visible" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
