CREATE TABLE "contact_settings" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"eyebrow" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"subtitle" text NOT NULL,
	"email_label" varchar(100) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone_label" varchar(100) NOT NULL,
	"phone" varchar(100) NOT NULL,
	"address_label" varchar(100) NOT NULL,
	"address" text NOT NULL,
	"hours_label" varchar(100) NOT NULL,
	"hours" varchar(255) NOT NULL,
	"social_heading" varchar(255) NOT NULL,
	"x_url" varchar(1000) DEFAULT '' NOT NULL,
	"instagram_url" varchar(1000) DEFAULT '' NOT NULL,
	"youtube_url" varchar(1000) DEFAULT '' NOT NULL,
	"twitch_url" varchar(1000) DEFAULT '' NOT NULL,
	"name_label" varchar(100) NOT NULL,
	"name_placeholder" varchar(255) NOT NULL,
	"form_email_label" varchar(100) NOT NULL,
	"form_email_placeholder" varchar(255) NOT NULL,
	"subject_label" varchar(100) NOT NULL,
	"subject_placeholder" varchar(500) NOT NULL,
	"message_label" varchar(100) NOT NULL,
	"message_placeholder" text NOT NULL,
	"submit_button_text" varchar(120) NOT NULL,
	"is_visible" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
